### PR TITLE
new solutions

### PR DESCRIPTION
**Pull request by luckyF24**

### CODE REVIEW

**Review by bilalilhan — APPROVED** [review]
good

**Review by bilalilhan — APPROVED** [review]

**Comment by bilalilhan** [comment]
Please, resolve the "Conflict"

**Review by luckyF24 — COMMENTED** [review]
looks good

**Review by bilalilhan — APPROVED** [review]

**Review by bilalilhan — APPROVED** [review]
nice

**Review by bilalilhan — APPROVED** [review]
.

**Review by Rubinah2023 — APPROVED** [review]
you did great

**Pull request closed without merging**
